### ISSUE TITLE
Project requires Guzzle 6.1.1

### ISSUE THREAD

**Issue by michaelbutler** [itskoko/koko-ai-php#2]
The Koko PHP library requires 6.1.1 due to a change here:
https://github.com/itskoko/koko-ai-php/commit/4a657dfbd35e8d35f5b86e16a9993720fcf0033d

However, 6.1.1 suffers from an HTTP_PROXY security vulnerability which was fixed in https://github.com/guzzle/guzzle/releases/tag/6.2.1, which might not affect everyone, but it's a good idea to allow a flexible version if possible, instead of requiring this one single version.

Perhaps you could use a version range, such as: `>=6.1.1 <6.3` which would allow end projects to optionally use version 6.2.1 and be cleared of the sec vuln.

**Comment by jed** [comment]
Thanks, @michaelbutler! I've updated the range to be more inclusive, and pushed it to Packagist.
